# ***************************生产配置**************************** #
# 当前激活的配置名称(请不要修改)
profile: prod
# 密码加密配置
jasypt:
  encryptor:
    password: ${JASYPT_ENCRYPTOR_PASSWORD:}
#性能配置
server:
  port: 9061
  tomcat:
    max-connections: 20000
    threads:
      max: 2000
      min-spare: 800
#Spring框架内部配置
spring:
  #数据源配置
  datasource:
    url: jdbc:mysql://52.187.38.88:3306/platon_browser_${version}?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: ENC(WdsbLfMqOVt4fifwvlrP/g==)
    password: ENC(YAS0fQLf2HgpNwy8EosToc3pBFUyvsla)
    #下面为连接池的补充设置，应用到上面所有数据源中
    #初始化大小，最小，最大
    initialSize: 5
    minIdle: 10
    maxActive: 100
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 30000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 100
  #Redis配置
  redis:
    ssl: true
    password: platscan
    database: 0
    cluster:
      max-redirects: 3
      nodes: 192.168.16.171:7001,192.168.16.171:7002,192.168.16.171:7000,192.168.16.172:7000,192.168.16.172:7001,192.168.16.172:7002
  #ES配置
  elasticsearch:
    high-level-client:
      hosts: 192.168.120.103,192.168.120.104,192.168.120.105
      port: 9200
      schema: http
      username: elastic
      password: changeme
#日志配置
logging:
  #日志级别
  level:
    org.springframework: error
    com.platon.browser: error
    com.platon.browser.service: error
    com.platon.browser.task: error
    com.platon.browser.client: error
    com.platon.browser.dao: error
  file:
    name: ./logs/${spring.application.name}-${version}-${profile}.log
#初始化链相关的配置
platon:
  # 地址HRP前缀
  addressPrefix: atp
  # 交易输入参数并行解码线程数
  txLogDecodeThreadNum: 200
  # Web3j访问地址
  web3j:
    #HTTP或WS
    protocol: HTTP
    addresses: 192.168.120.151:6789,192.168.120.151:6790
  # 质押节点统计年化率最多取多少个连续周期
  maxSettlePeriodCount4AnnualizedRateStat: 4
  #PlatON初始总发行量(ATP)
  initIssueAmount: 100000000
  #每年固定增发比例
  addIssueRate: 0.05
  #每年增发分配给激励池的比例
  incentiveRateFromIssue: 0.4
  #每个共识轮中回退多少个块是选举下一轮验证人的时机
  electionBackwardBlockCount: 20
  #10年内计算士基金会向激励池填充额度: <第几年-补贴金额(ATP)>
  foundationSubsidies: {
    '1':0,
    '2':0,
    '3':0,
    '4':0,
    '5':0,
    '6':0,
    '7':0,
    '8':0,
    '9':0
  }
  # 初始内置节点默认质押金额(ATP)
  defaultStakingLockedAmount: 10500
  #区块最大Gas限制
  maxBlockGasLimit: 100800000
  #提案url参数模板
  proposalUrlTemplate: https://github.com/PlatONnetwork/GalaxyRally/blob/master/PIPs/PIP-%s.md
  #proposalUrlTemplate: https://github.com/PlatONnetwork/PIPs/PIP-%s.md
  #keysBase网址
  keyBase: https://keybase.io/
  #keyBase api
  keyBaseApi: _/api/1.0/user/lookup.json?key_suffix=
  #链id
  chainId: 201018
  #Redis命名空间
  redis-namespace: browser:${version}:${profile}
  #Es索引命名空间
  es-namespace: browser_${version}_${profile}

recaptchaUrl: https://recaptcha.net/recaptcha/api/siteverify?secret=6Lf8KLcUAAAAAPyHZfa7oeWjdMSyvgDHUUeYf01Z&response=%s
isRecaptcha: false
limit:
  num: 10
output:
  file:
    url: D:/